owner: SethuK06
repo: Upptime

sites:
  - name: TMV
    url: https://www.1tamilmv.tf/
  - name: TBL
    url: https://1tamilblasters.dad/
  - name: BTDigg
    url: https://btdig.com/index.htm
  - name: TGX
    url: https://torrentgalaxy.to/

assignees:
  - SethuK06

status-website:
  theme: dark
  logoUrl: https://upptime.js.org/img/icon.svg
  baseUrl: /Upptime
  name: Movie Website Status
  introTitle: "**Find the status of all movie resources here**"
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/SethuK06/Upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowschedule:  
  uptime: "*/30 * * * *"  
  graphs: "*/30 * * * *"  
  responseTime: "*/30 * * * *"  
  staticSite: "*/30 * * * *"  
  summary: "*/30 * * * *"
  updateTemplate: "*/30 * * * *"
  updates: "*/30 * * * *"

